stages:
  - build
  - test
  - deploy

conda:
  image: continuumio/miniconda3:latest
  before_script:
    - conda install conda-build
    - conda config --set anaconda_upload no
  stage:  build
  script:
    - cd conda
    - conda build --python=3.6 .
  only:
  - py23

