stages:
  - build
  - test
  - deploy

conda:
  image: python:3.6-alpine

  before_script:

    - chmod +x conda-pipeline/miniconda.sh
    - exec conda-pipeline/miniconda.sh
    # - apt-get install gcc
    - apt-get install swig
    #- conda env create -f environment.yaml
    #- source activate myenv
    #- conda install conda-build
    - conda config --set anaconda_upload no
    - conda build . --output

  stage:  build

  script:
    - cd conda
    - conda build --python=3.7 .
    - conda build --python=3.6 .
    - conda build --python=3.4 .
    - conda build --python=2.7 .
    - mv dist

  artifacts:
    paths:
    - conda/dist



  only:
  - py23

pip:
  image: python:3.6

  before_script:
  - apt-get install gcc
  - apt-get update -q -y
  - apt-get install -y swig
  - pip install -r pip-pipeline/requirements.txt

  stage:  build

  artifacts:
    paths:
    - dist

  script:
  - python setup.py install

  only:
  - never