stages:
  - build
  - test
  - deploy

conda:
  image: python:3.6

  before_script:
    - apt-get update -q -y
    - apt-get install -y  gcc
    - apt-get install -y swig
    - chmod +x conda-pipeline/miniconda.sh
    - ./conda-pipeline/miniconda.sh

    #- conda env create -f environment.yaml
    #- source activate myenv


  stage:  build

  script:
    - conda install conda-build
    - conda config --set anaconda_upload no
    - cd conda-pipeline
    - conda build --python=3.7 .
    - conda build --python=3.6 .
    - conda build --python=3.4 .
    - conda build --python=2.7 .
    - conda build . --output

  artifacts:
    paths:
    - /opt/conda/conda-bld/linux-64/



  only:
  - py23

pip:
  image: python:3.6

  before_script:
  - apt-get update -q -y
  - apt-get install -y  gcc
  - apt-get install -y swig
  - pip install -r pip-pipeline/requirements.txt

  stage:  build

  artifacts:
    paths:
    - dist

  script:
  - python setup.py install

  only:
  - never