stages:
  - build
  - test
  - deploy

conda:
  image: continuumio/miniconda3:latest

  before_script:
    - apt-get install gcc
    - apt-get install swig
    #- conda env create -f environment.yaml
    #- source activate myenv
    #- conda install conda-build
    - conda config --set anaconda_upload no

  stage:  build

  script:
    - cd conda
    - conda build --python=3.7 .
    - conda build --python=3.6 .
    - conda build --python=3.4 .
    - conda build --python=2.7 .

  only:
  - py23

pip:
  image: python:3.6

  before_script:
  - apt-get install gcc
  - apt-get update -q -y
  - apt-get install -y swig
  - pip install -r pip-pipeline/requirements.txt

  stage:  build

  script:
  - python setup.py install

  only:
  - py23