branches:
    only:
        - py23


sudo: required
language: generic
services:
  - docker

os:
  - linux
  - osx



env:
  # Build and test package on all supported python version
  #- BUILD_TARGET=3.7
  - BUILD_TARGET=3.6 
  #- BUILD_TARGET=2.7


install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes
  - conda install conda-build


script:
  - conda config --set anaconda_upload no
  - conda build conda-pipeline --python=$BUILD_TARGET
  #- conda activate
  #- python scripts/run_tests.py --format-only

#after_success:
#  - codecov

#deploy:
#  provider: releases
#  skip_cleanup: true
#    api_key:
#      secure: "L9XC6r4Qr02WvBU+Xk795S9X7WyZUD3p6Sr7Mvq7+Sgg1TslxzXcHElTxBdkdg6SR1peru6sKHdT1gUp+Nwwebiv5t2b9WLGpIbxnG92ni5bM1G4EDl/pTSh2RTTv7+Xf7FW06brT1f2XrkQhkxo7qUu4oZ0nMcOaXfhhUZVY0xaKQ2GFsdZKWgx8JAbVBS3g+Ki+VNQZ+QphFA4ZhleVq+0eCrvCQxntclc//0UFVrS5qTvY/L55ZrYEUdQ8YSt6yhGey3APQWMfDmXUIJayxPMdaWXvyj8ypcaA6z9fQcdjPvdKaX6mYm3FB/Kbn09IorB+RcednDnFTnwnOH/UzUzGH02L2jItfiinHiwEc9k5cfpcWnDFW9NZVNq2qYl5UCPOruU2FsAzFJGZJ33pN7iuwFFO/vALJVA4pZzRRENauT9yfKQVdPVZU+XsT28uBIfouLKuyYaTNVA1CiuNnleuS6SCxZnRC3w/mdTil1X4mZXi7iGmG10RxzAwrUhVpuIkAH5P5VB+jErLgK2In2CYdZo7BotihxQn0aiKviv6j+JvyjsmMm1ZLKYiag227WQnOODnOydtIMlvQiSg3rto/pxrSwoOWM7Wkep8r8AALHLkdHIQNiBafToyoymBgPEy1NuSn3wpawUTGC6fh5Hl5W+rz1WXQ9md7gTFqs="
#    file_glob: true
#    file:
#    - "conda-build/*"
#    on:
#      tags: False



