branches:
    only:
        - py23


sudo: required
language: generic
services:
- docker

os:
- linux
- osx



env:
  # Build and test package on all supported python version
  - BUILD_TARGET=3.7
  - BUILD_TARGET=3.6 
  - BUILD_TARGET=2.7


install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes
  

script:
  - conda build conda-pipeline --python=$BUILD_TARGET
  #- conda activate
  #- python scripts/run_tests.py --format-only

#after_success:
#  - codecov