addons:
  artifacts:
    # ...
    debug: true

branches:
    only:
        - py23


sudo: required
language: generic
services:
  - docker

os:
  #- linux
  - osx



env:
  # Build and test package on all supported python version
  #- BUILD_TARGET=3.7
  - BUILD_TARGET=3.6 
  #- BUILD_TARGET=2.7


install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes
  - conda install conda-build


script:
  - conda config --set anaconda_upload no
  #- conda build conda-pipeline --python=$BUILD_TARGET
  - echo $PWD
  - mkdir dist
  - mkdir dist/$BUILD_TARGET
  #- mkdir dist/3.6
  #- mkdir dist/3.4
  #- mkdir dist/2.7
  - conda config --set anaconda_upload no

  - conda build conda-pipeline --python=$BUILD_TARGET
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then OS_FLAG=Linux; else OS_FLAG=osx-64; fi
  - cp /Users/travis/miniconda/conda-bld/$OS_FLAG/* dist/$BUILD_TARGET




  #- conda activate
  #- python scripts/run_tests.py --format-only

#after_success:
#  - codecov

deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${api_key}
  #  secure: "Gcw1TPL2E5gVKJTGbKkIob+zP6sRIEDniVO1Xdekt1V2wUHW9Kh1UDOAJ8c+mPEjiesqVS/NhRmbVVEREF0HQKLQueNWsyrXi+t9//ezbSDAkUH8NldNf2eYkBX6U2rUJuUpKJt+qylJOw/IHODMDCP+Md/9r64STOi04I77D/v+/iqEkve0PwrBquR9TYbm8i3h3MAdBIKcsNznwKbnbyxmku2J6tvBT5HZEsfot/uMZQhjhrKDaULKrVKV6XF0J7VD/AKkdEfI7htAveYJ/FA2P8t5B6B3Wc4BbgnlxxADtaVXHKFiJwkFU8QmV/dF/aTRANiydJyDWCYlbqZnl9fT+hV74DnxXw+o3SPckMbuQZjfxTa+0XeVOLI9RgoLN0WRLiYWyo5W02OHdOkI48/Yv6Z0MOlsQpTQYspbTSACtImW1l0198uAV0vjg00DxQYRuvgCKZ3rnV21BOLPGW2HETtN8bAegZzU1CWaN5YuPe/QvmheBXNJbAdRZ8dpOL/ohFt7NQjxbPIp41C2KjAut5T3q2PjXNl2YQnB9EKV5tyRX5eIpZjcq0i9vFSQDSQZu7E7q2NZZTaw0wZjSdTLyhj5SSFExyS7mMmt4TX1lgS52lWy7/piEkY0Jm4eEeN3XKkKwqTGofbpjeg8RxKBvZrHyW4b+clPpYYn7OE="
  file_glob: true
  file:
    - "dist/*"
  on:
    tags: False
    #all_branches: True
    branch: py23

