package:
  name: jetset
  version: "1.1.0"

source:
  git_url: https://github.com/andreatramacere/jetset.git
  git_rev: develop


build:
  # noarch_python: True
  preserve_egg_dir: True

requirements:

  build:
    - swig
    - python
     
#
  run:
  - scipy
  - numpy
  - astropy>=4.0
  - matplotlib
  - future
  - iminuit
  - corner
  - six
  - emcee
  - pyyaml
  - pyqt
#
#tests:
#    imports:
#        - jetset
#        - jetset.jetmodel
#

#  # commands:
#    # You can put tests commands to be run here.  Use this to tests that the
#    # entry points work.
#
#
#  # You can also put a file called run_test.py in the recipe that will be run
#  # at tests time.
#
#  requires:
#    - nose >=1.3.7
#    # Put any additional tests requirements here.  For example
#    # - nose



about:
  home: https://github.com/andreatramacere/jetset
  license: BSD-3
  summary: ''
  license_family: BSD

extra:
  recipe-maintainers:
    - andreatramacere