about:
  home: https://gitlab.com/andreatramacere/jetset,ttps://github.com/andreatramacere/jetset
  license: BSD-3
  license_family: BSD
  summary: ''
build:
  preserve_egg_dir: true
extra:
  recipe-maintainers:
  - andreatramacere
package:
  name: jetset
  version: 1.0.2a9
requirements:
  build:
  - swig
  - python {{PY_VER}}*
source:
  git_rev: py23
  git_url: https://gitlab.com/andreatramacere/jetset.git
